In [1]:
'''Code to plot an EDS spectra anaylsis from a master csv file
Code by Scott Gleason, University of New South Wales (UNSW), Australia 
S.Gleason@student.unsw.edu.au, April 2015'''

'''Make a plot function (lesson 6), run it trough a loop (lesson 4), 
add glob libary for searching
always add COMMENTS within function so help(function) command can be used'''

'Make a plot function (lesson 6), run it trough a loop (lesson 4), \nadd glob libary for searching\nalways add COMMENTS within function so help(function) command can be used'

In [2]:
'imports numpy and matplotlib libaries into code'
import numpy as np
import matplotlib.pyplot as plt

In [3]:
cd 'C:\Users\z3492622\Documents\PhD Project\Results'

C:\Users\z3492622\Documents\PhD Project\Results


In [4]:
cd 'SEM\\2015-04-04 (T2 3 5)\EDS Anaylsis\Python Code Test'

C:\Users\z3492622\Documents\PhD Project\Results\SEM\2015-04-04 (T2 3 5)\EDS Anaylsis\Python Code Test


In [5]:
'File to be ploted stored as a variable and printed'
Fname = 'TestCodeFile2.csv'

print 'File is:'
print Fname

File is:
TestCodeFile2.csv


In [6]:
'''Loads file as a variable into numpy,
stores it as a as an array and prints it (as a check)'''

'''These variable define the array limits
StartRow is the row data starts on
LastColumn is the column data ends on
(i.e. this cuts unneed instriment data, dates, etc)'''
StartRow = 26
LastColumn = 3

'Creats data variable, should not have to edit this string'
dataMatrix = np.loadtxt(Fname, delimiter = ',', 
                  skiprows = StartRow - 1, usecols = range(0, LastColumn, 1))
print dataMatrix

[[  0.00000000e+00  -4.74997495e-01   0.00000000e+00]
 [  1.00000000e+00  -4.69996995e-01   0.00000000e+00]
 [  2.00000000e+00  -4.64996495e-01   0.00000000e+00]
 ..., 
 [  4.09300000e+03   1.99920490e+01   0.00000000e+00]
 [  4.09400000e+03   1.99970495e+01   0.00000000e+00]
 [  4.09500000e+03   2.00020500e+01   0.00000000e+00]]


In [7]:
def getColumn(filename, column):
    '''Defines function to direct code to specific columns within data
    First argument is the filename, second argument is the column'''
    
    'Uses dataMatrix path defined above'
    return [result[column] for result in dataMatrix]

In [8]:
'Define X & Y axis data to be ploted'
xAxisData = getColumn(Fname, 1)
yAxisData = getColumn(Fname, 2)

In [9]:
'Generates plot of data, and chart layout'

'Define Plot layout, axis lables, legends, etc'
plt.figure("Counts/keV")
plt.title("Counts/keV", fontsize = 22)
AxisFontSize = 14
plt.xlabel("keV", fontsize = AxisFontSize)
plt.ylabel("Counts", fontsize = AxisFontSize)
LineType = 'g'

'Sets axis upper limit'
xMax = 20
yMax = 7000

'Generates plot'
plt.plot(xAxisData, yAxisData, LineType, linewidth = 1.8)
plt.axis([0, xMax, 0, yMax])
plt.show()